title: My Journey in 한국어!
description: An accountability diary documenting my journey in learning the Korean Language
theme: just-the-docs

url: https://randalleverhart.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
